rectify

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,6 +15,8 @@ jobs:
           npm install
           npm run build
       - name: run Lighthouse CI Benchmarks
-        run: npm run ci:lighthouse
+        run: 
+            npm install -g @lhci/cli@0.8.x
+            lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
